import type { Metadata } from "next";
import { Geist, Geist_Mono,Outfit as OutfitFont } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./Provider";
import { Suspense } from "react";
import Loading from "./_components/Loading";

const Outfit = OutfitFont({
  variable: "--font-outfit",
  subsets: ["latin"],
});

 const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${Outfit.className}  antialiased`}
      >
        <Provider>
        <Suspense fallback={<Loading />}>
        {children}
        </Suspense>
        </Provider>
      </body>
    </html>
    </ClerkProvider>
  );
}
